api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views


router = routers.DefaultRouter()
router.register(r'messages', views.MessagesView, basename='messages')
router.register('room_messages', views.RoomMsgsView, basename='room_messages')
router.register(r'users', views.UsersView)
router.register(r'monitor', views.MonitorView)

app_name = 'api'
urlpatterns = [
	path('', include(router.urls)),
]

chat/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'chat'
urlpatterns = [
    path(r'', login_required(views.ChatView.as_view()), name='chat'),
    path(r'<int:friend_id>', login_required(views.ChatWithFriendView.as_view()), name='chat_with_friend'),
    path(r'room/<int:room_id>', login_required(views.RoomView.as_view()), name='room'),
 #   path('get_messages/<int:friend_id>', views.get_messages, name='get_messages'),
#    path('addFriend/<int:friend_id>', views.add_friend, name='addFriend'),
    path(r'send', login_required(views.send), name='send'),
    path(r'new_room', views.create_room, name='create_room'),
    path(r'add_friend', views.add_friend, name='add_friend'),
    path(r'delete_friend', views.delete_friend, name='delete_friend'),
    ]

chatapp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls'), name='chat'),
    path('api/', include('api.urls'), name='api'),
    path('', include('website.urls'), name='index')
]

website/urls.py
from django.urls import path
from . import views


app_name = 'website'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('monitor', views.MonitorView.as_view(), name='monitor'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('signup', views.SignupView.as_view(), name='signup'),

    ]

website/models.py
from django.db import models

website/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect, reverse
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from chat.models import Profile


class IndexView(TemplateView):
    template_name = 'website/index.html'

    def get_context_data(self, **kwargs):
        if self.request.user.is_authenticated:
            return {'user': self.request.user}


class LoginView(TemplateView):
    template_name = 'website/login.html'
    form = AuthenticationForm

    def post(self, request, *args, **kwargs):
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            request.session.set_expiry(87600)
            login(request, user)
            return redirect('chat:chat')
        else:
            return render(request, 'website/login_failed.html')

    def get_context_data(self, **kwargs):
        return {'form': self.form}


class LogoutView(TemplateView):
    template_name = 'website/logout.html'

    def get(self, request, *args, **kwargs):
        logout(request)
        return render(request, self.template_name)


class SignupView(TemplateView):
    template_name = 'website/signup.html'
    form = UserCreationForm

    def post(self, request, *args, **kwargs):
        signup_form = self.form(request.POST)
        if signup_form.is_valid():
            form_data = signup_form.cleaned_data
            user = User.objects.create_user(username=form_data['username'], password=form_data['password1'])
            p = Profile.objects.create(user=user)
            print(f'user {user}, p: {p}')
            if user is not None:
                login(request, user)
                return redirect('chat:chat')
        else:
            print(f'Errors {signup_form.errors}')
            return render(request, 'website/signup_failed.html', {'errors': signup_form.errors})

    def get_context_data(self, **kwargs):
        return {'form': self.form}


class MonitorView(TemplateView):
    template_name = 'website/monitor.html'

website/templates/website/_head.html
{% load static %}
<head>
    <title> Chat app </title>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <script
        src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous">
    </script>

        <!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>

    <script
        src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous">
    </script>
    <script
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />


</head>

website/templates/website/_login_form.html
<form id="login_form" method="POST" action="#">
    <h2 id="login_title"> Log in </h2>
    {% csrf_token %}
    {{ form.as_p }}
    <button id="login_button" type="submit"> Login </button>
</form>

website/templates/website/_navbar.html
<div id="navbar" class="w3-top w3-bar w3-black w3-card">
    <a href="{% url 'chat:chat' %}" class="w3-bar-item w3-button w3-padding-large"> Chat </a>

    {% if user.is_authenticated %}
        <a href="{% url 'website:logout' %}" class="w3-bar-item w3-button w3-padding-large"> Log Out </a>
    {% else %}
        <a href="{% url 'website:login' %}" class="w3-bar-item w3-button w3-padding-large"> Log In </a>
        <a href="{% url 'website:signup' %}" class="w3-bar-item w3-button w3-padding-large"> Sign Up </a>
    {% endif %}
</div>

website/templates/website/_signup_form.html
<form method="post" action="#" id="sign_up_form">
    <h2> Sign up </h2>
    {% csrf_token %}
        {{ form.as_p }}

    <button type="submit" value="submit" id="signup_button"> Sign up </button>
</form>

website/templates/website/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

{% block head %}
    {% include 'website/_head.html' %}
{% endblock %}

<body>

{% block navbar %}
    {% include 'website/_navbar.html' %}
{% endblock %}


{% block content %}
{% endblock %}

{% block js %}
{% endblock %}
</body>



</html>

website/templates/website/index.html
{% extends 'website/base.html' %}



{% block content %}


    <h3>
        Welcome to chat app!
    </h3>


{% endblock %}

website/templates/website/login.html
{% extends 'website/base.html' %}
{% load static %}

<div id="login_div">
{% block content %}
    {% include 'website/_login_form.html' %}
{% endblock %}
</div>

website/templates/website/login_failed.html
{% extends 'website/base.html' %}

{% block content %}
{% include 'website/_login_form.html' %}
<div id="login_failed">
    <p>
        Login failed. Please try again.
    </p>
</div>
{% endblock %}

website/templates/website/login_required.html
{% extends 'website/base.html' %}

{% block content %}
    <h3>
        You need to log in to use watchlist and portfolio.
    </h3>
    <h3>
        <a href="{% url 'website:login' %}"> Login page </a>
    </h3>
    <h3>
        <a href="{% url 'website:signup' %}"> Sign up page </a>
    </h3>
{% endblock %}

website/templates/website/logout.html
{% extends 'website/base.html' %}

{% block navbar %}
    {% include 'website/_navbar.html' %}
{% endblock %}

{% block content %}
<p>
    You have successfully logged out. Click <a href="{% url 'website:login' %}">here</a> to log in again.
</p>
{% endblock %}

website/templates/website/signup.html
{% extends 'website/base.html' %}

{% block content %}
    <div id="signup_form">
        {% include 'website/_signup_form.html' %}
    </div>
{% endblock %}

website/templates/website/signup_failed.html
{% extends 'website/base.html' %}

{% block content %}
    <div id="signup_failed_form">
        <button id="back_to_signup_button" onclick="location.href='{% url 'website:signup' %}'">
            Back
        </button>
    </div>

    <div id="signup_errors">
        <p>
            Signup failed due to following errors:
        </p>
            {% for key, error in errors.items %}
        <p>
            {{ key }} : {{ error }}
        </p>
            {% endfor %}
        <p>
            Please try again.
        </p>

    </div>
{% endblock %}