api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views


router = routers.DefaultRouter()
router.register(r'messages', views.MessagesView, basename='messages')
router.register('room_messages', views.RoomMsgsView, basename='room_messages')
router.register(r'users', views.UsersView)
router.register(r'monitor', views.MonitorView)

app_name = 'api'
urlpatterns = [
	path('', include(router.urls)),
]

chat/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'chat'
urlpatterns = [
    path(r'', login_required(views.ChatView.as_view()), name='chat'),
    path(r'<int:friend_id>', login_required(views.ChatWithFriendView.as_view()), name='chat_with_friend'),
    path(r'room/<int:room_id>', login_required(views.RoomView.as_view()), name='room'),
 #   path('get_messages/<int:friend_id>', views.get_messages, name='get_messages'),
#    path('addFriend/<int:friend_id>', views.add_friend, name='addFriend'),
    path(r'send', login_required(views.send), name='send'),
    path(r'new_room', views.create_room, name='create_room'),
    path(r'add_friend', views.add_friend, name='add_friend'),
    path(r'delete_friend', views.delete_friend, name='delete_friend'),
    ]

chatapp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls'), name='chat'),
    path('api/', include('api.urls'), name='api'),
    path('', include('website.urls'), name='index')
]

chat/models.py
from django.db import models
import datetime


class Profile(models.Model):
	user = models.OneToOneField('auth.User', on_delete=models.CASCADE, related_name='user_profile')

	messages = models.ManyToManyField('chat.Message', related_name='user_messages', blank=True)
	rooms = models.ManyToManyField('chat.Room', related_name='user_rooms', blank=True)
	friends = models.ManyToManyField('self', blank=True)

	def __str__(self):
		return self.user.get_username()


class Message(models.Model):
	sender = models.ForeignKey('chat.Profile', on_delete=models.CASCADE, unique=False, related_name='message_sender',
							    blank=True)
	recipient = models.ForeignKey('chat.Profile', on_delete=models.CASCADE, unique=False, default=1,
								   related_name='message_recipient', blank=True)
	room = models.ForeignKey('chat.Room', on_delete=models.CASCADE, default=1, related_name='message_room', blank=True)
	content = models.TextField(max_length=1000, blank=False)
	timestamp = models.DateTimeField(blank=True)
	delivered = models.BooleanField(default=False)
	read = models.BooleanField(default=False)
	destruct_timer = models.IntegerField(blank=True, null=True, default=50)

	def __str__(self):
		return str(self.timestamp) + ' ' + self.sender.user.get_username() + ': ' + str(self.content)


class Room(models.Model):
	creator = models.ForeignKey('chat.Profile', on_delete=models.CASCADE, related_name='room_creator')
	room_name = models.CharField(max_length=32)
	creation_date = models.DateTimeField()
	private = models.BooleanField(default=False)
	users = models.ManyToManyField('chat.Profile', related_name='room_users', blank=True)

chat/forms.py
from django import forms



class FindUsersForm(forms.Form):
    name = forms.CharField(label='Username', max_length=32,
                           widget=forms.TextInput(attrs={'placeholder': 'Find users/rooms'}))


class CreateRoomForm(forms.Form):
    room_name = forms.CharField(max_length=16, label='Create room', widget=forms.TextInput(attrs={'placeholder': 'Room name..'}))
    private = forms.BooleanField(required=False)

chat/views.py
import datetime
from itertools import chain

from django.shortcuts import render, HttpResponseRedirect, redirect, HttpResponse
from django.http import JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import TemplateView
from .models import Message, Room, Profile
from .forms import CreateRoomForm, FindUsersForm
from .utils import see_users, clear_history


class ChatView(TemplateView):
    template_name = 'chat/chat.html'
    find_users_form = FindUsersForm
    create_room_form = CreateRoomForm

    def post(self, request, *args, **kwargs):
        user = Profile.objects.get(user=request.user)
        if 'add_friend' in str(request.POST):
            friend = Profile.objects.get(user=User.objects.get(id=request.POST['add_friend']))
            if friend not in user.friends.all():
                user.friends.add(friend)
                user.save()
                return HttpResponseRedirect(reverse('chat:chat_with_friend', args=(friend.id,)))
        return HttpResponseRedirect(reverse('chat:chat'))

    def get_context_data(self, *args, **kwargs):
        user = self.request.user
        profile = user.user_profile
        users_online = see_users()
        friends = [(f.user.username, f.id, f.user in users_online) for f in profile.friends.all()]
        friend = None
        room = None
        owned_rooms = Room.objects.filter(creator=profile)
        priv_rooms = profile.rooms.all()
        pub_rooms = Room.objects.filter(private=False)
        rooms = owned_rooms.union(priv_rooms, pub_rooms)



        search_results = []
        if 'name' in str(self.request.GET):
            find_form = FindUsersForm(self.request.GET)
            if find_form.is_valid():
                form_data = find_form.cleaned_data
                search_results = User.objects.filter(username__icontains=form_data['name'])
            else:
                print(f'Errors: {find_form.errors}')
        return {'friend': friend, 'friends': friends, 'pub_rooms': pub_rooms, 'rooms': rooms,
                'priv_rooms': priv_rooms, 'owned_rooms': owned_rooms, 'room': room, 'online_users': users_online,
                'create_room_form': self.create_room_form, 'find_friends_form': self.find_users_form,
                'search_results': search_results}


def send_to_room(request):
    if 'room_id' in str(request.POST):
        room = Room.objects.get(id=request.POST['room_id'])
        Message.objects.create(sender=sender, recipient=sender, content=message, timestamp=date, to_room=True,
                               destruct_timer=destr_timer, room=room)
        return HttpResponseRedirect(reverse('chat:room', args=(room.id,)))


def send(request):
    user = Profile.objects.get(user=request.user)
    print(request.POST)
    if 'friend_id' in str(request.POST) and 'msg_text' in str(request.POST):
        friend = Profile.objects.get(id=request.POST['friend_id'])
        date = datetime.datetime.now(tz=datetime.timezone(datetime.timedelta(hours=1)))
        Message.objects.create(sender=user, recipient=friend, content=request.POST['msg_text'],
                               timestamp=date)
        # destruct_timer=request.POST['destr_timer']
        return HttpResponseRedirect(reverse('chat:chat_with_friend', args=(friend.id,)))


class ChatWithFriendView(ChatView):

    def post(self, request, *args, **kwargs):
        user = Profile.objects.get(user=request.user)
        friend = Profile.objects.get(id=kwargs['friend_id'])
        if 'clear_history' in str(request.POST):
            clear_history(user.id, friend.id)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['friend'] = Profile.objects.get(id=kwargs['friend_id'])
        return context


class RoomView(ChatView):
    model = Room
    create_room_form = CreateRoomForm


    def get_context_data(self, room_id, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        room = Room.objects.get(id=room_id)
        context['room'] = room
        context['messages'] = Message.objects.filter(room=room)
        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        if 'join_room_btn' in str(request.POST):
            room = Room.objects.get(id=request.POST['join_room_btn'])
            profile = Profile.objects.get(user=request.user)
            profile.rooms.add(room)
            profile.save()

        return HttpResponseRedirect(reverse('chat:room', args=(context['room'].id, )))



def delete_friend(request):
    user = Profile.objects.get(user=request.user)
    if request.method == "POST" and 'del_friend_btn' in str(request.POST):
        friend = Profile.objects.get(id=request.POST['del_friend_btn'])
        if friend in user.friends.all():
            user.friends.remove(friend)
            user.save()
        return HttpResponseRedirect(reverse('chat:chat'))


def add_friend(request):
    if request.method == "POST" and 'add_friend' in str(request.POST):
        user = Profile.objects.get(user=request.user)
        friend = Profile.objects.get(user=User.objects.get(id=request.POST['add_friend']))
        if friend not in user.friends.all():
            user.friends.add(friend)
        return HttpResponseRedirect(reverse('chat:chat'))


def create_room(request):
    if request.method == "POST":
        room_form = CreateRoomForm(request.POST)
        if room_form.is_valid():
            form_data = room_form.cleaned_data
            form_data['creator'] = request.user.user_profile
            form_data['creation_date'] = datetime.datetime.now(datetime.timezone.utc)
            r = Room.objects.create(**form_data)
        else:
            print(f'errors: {room_form.errors}')

        return HttpResponseRedirect(reverse('chat:room', args=(r.id, )))














#old
def get_messages(request, friend_id):
    tz_info = datetime.datetime.now(datetime.timezone.utc).astimezone().tzinfo
    user = request.user
    recipient = User.objects.get(id=friend_id)
    msgs = []
    sent_msgs = Message.objects.filter(sender=user, recipient=recipient).values()
    msgs.append(sent_msgs)
    if not user == recipient:
        received_msgs = Message.objects.filter(sender=recipient, recipient=user).values()
        msgs.append(received_msgs)

    msgs = sorted(
        chain(*msgs),
        key=lambda instance: instance['timestamp'])

    for msg in msgs:
        if msg['destruct_timer']:
            msg_obj = Message.objects.get(id=msg['id'])
            msg_date = msg['timestamp']
            now = datetime.datetime.now(tz=tz_info)
            delta = (now - msg_date).total_seconds()
            msg['destruct_timer'] = (msg_obj.destruct_timer - delta).__round__(2)
            if delta > msg['destruct_timer']:
                Message.objects.filter(id=msg['id']).delete()
                msgs.remove(msg)

        msg['sender_id'] = User.objects.get(id=msg['sender_id']).username
    return JsonResponse({'messages': msgs})



@login_required
def chat(request, friend_id):
    print('chat2')
    context = {}
    user = request.user
    friends = user.friends.all()
    recipient = MyUser.objects.get(id=friend_id)
    context['profile'] = user
    context['friends'] = friends
    context['recipient'] = recipient
    context['find_users'] = FindUsersForm()
    context['search_results'] = []
    sent_msgs = Message.objects.filter(sender=user, recipient=recipient)
    received_msgs = Message.objects.filter(sender=recipient, recipient=user)
    msgs = sorted(
        chain(sent_msgs, received_msgs),
        key=lambda instance: instance.timestamp)
    context['messages'] = msgs
    return render(request, 'chat/chat.html', context)




@login_required
def messenger(request):
    context = {}
    user = request.user
    friends = user.friends.all()
    context['profile'] = profile
    context['friends'] = friends
    context['recipient'] = None
    context['find_users'] = FindUsersForm()
    context['search_results'] = []
    if request.method == 'GET':
        if 'find_users' in str(request.GET):
            find_form = FindUsersForm(request.GET)
            if find_form.is_valid():
                form_data = find_form.cleaned_data
                name = form_data['name']
                context['search_results'] = MyUser.objects.filter(username__icontains=name)
                print(context['search_results'])
            else:
                print(f'error {find_form.errors}')
    else:
        friend = MyUser.objects.get(user=MyUser.objects.get(id=request.POST['add_friend']))
        if not user.friends.filter(user=friend).exists():
            user.friends.add(friend)
    return render(request, 'chat/chat.html', context)

chat/templates/chat/_add_friend.html
<form id="find_friends_form" method="get" action="#">
    <h3 id="friends_search_label">
        Find users
    </h3>
    {{ find_users.as_p }}

    <button id="find_friends_button" type="submit" name="find_users">
        Search
    </button>
</form>

<h3 id="search_results_label">
    Search results
</h3>
<ul id="friends_search_results" class="w3-ul">
    {% for user in search_results %}
        <li id="{{ user.id }}">
            <div class="search_result_name">

                    {{ user.username }}

            </div>
            <div class="search_result_buttons">

                <form id="add_friend_form{{ user.id }}" method="post" action="#">
                    {% csrf_token %}
                    <button id="add_friend{{ user.id }}" type="submit" name="add_friend" value="{{ user.id }}" class="add_button">
                        Add
                    </button>
                </form>
            </div>
        </li>
    {% endfor %}
</ul>

chat/templates/chat/_chat_top.html
 <div id="chat_top_div">

        <h3 id="chat_header">
            {% if room %}
                Room {{ room.room_name }}
            {% elif friend %}
                Chat with {{ friend.user }}
            {% endif %}
        </h3>
        <form id="clear_chat_form" method="post" action="#">
            {% csrf_token %}
            <button id="clear_chat_history" type="submit" name="clear_history" value="{{ friend.id }}">
                Clear history
            </button>
        </form>

        <div id="destruct_div">
            <h4 id="destruct_text">
                Destruct timer
            </h4>

            <select id="destruct_select">
                <option id="des_option_off" name="des_option_off" value="0">
                    Off
                </option>
                <option id="des_option_5s" name="des_option_5s" value="5">
                    5s
                </option>
                <option id="des_option_1m" name="des_option_1m" value="60">
                    1m
                </option>
                <option id="des_option_5m" name="des_option_5m" value="300">
                    5m
                </option>
                <option id="des_option_30m" name="des_option_30m" value="1800">
                    30m
                </option>
                <option id="des_option_1h" name="des_option_1h" value="3600">
                    1h
                </option>
                <option id="des_option_2h" name="des_option_2h" value="7200">
                    2h
                </option>
                <option id="des_option_24h" name="des_option_24h" value="86400">
                    24h
                </option>
            </select>

        </div>


    </div>

chat/templates/chat/_chat_window.html
    <div id="chat_textarea_div">
        <textarea id="chat_textarea" disabled="disabled">
        </textarea>
    </div>

chat/templates/chat/_friend_list.html
<div id="friend_list">
    <h2>
        Friends
    </h2>


<table id="friend_list_table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Online
            </th>
        </tr>
    </thead>
    <tbody>


            {% for friend in friends %}
                <tr>
                    <td>
                        <h5>
                            <a href="/chat/{{ friend.1 }}"> {{ friend.0 }} </a>
                        </h5>
                    </td>
                    <td>
                        {% if friend.2 %}
                            <img src="{% static 'img/green-dot.png' %}" alt="x" width="18px" height="18px">
                        {% else %}
                            <img src="{% static 'img/red-dot.png' %}" alt="x" width="18px" height="18px">
                        {% endif %}

                    </td>
                    <td>
                        <form id="del_friend_form_{{ friend.1 }}" method="post" action="/chat/delete_friend">
                            {% csrf_token %}
                            <button name="del_friend_btn" value="{{ friend.1 }}" type="submit">
                                X
                            </button>

                        </form>
                    </td>
                </tr>
            {% endfor %}


    </tbody>
</table>


</div>

<div id="find_friends">
    <h3 id="find_friends_header">
        Find friends
    </h3>
    <form id="find_friends_form" method="get" action="">
        {% csrf_token %}
        {{ find_friends_form.as_p }}
        <button type="submit" id="find_friends_btn">
            Search
        </button>
    </form>
    {% if search_results %}
    <table id="search_results_table">
        <tbody>
            {% for result in search_results %}

                <tr>
                    <td>
                        {{ result.username }}
                    </td>
                    <td>
                        <form id="add_friend_form_{{ result.id }}" action="{% url 'chat:add_friend' %}" method="post">
                            {% csrf_token %}
                            <button name="add_friend" value="{{ result.id }}" type="submit">
                                Add friend
                            </button>

                        </form>
                    </td>
                </tr>

            {% endfor %}

        </tbody>
    </table>
    {% endif %}
</div>

chat/templates/chat/_message_form.html
<div id="msg_div">
    <form id="msg_form" method="post" action="">
        {% csrf_token %}
        <input id="friend_id" type="hidden" name="friend_id" value="{{ friend.id }}">
        <button id="clear_msg" type="reset"> Clear </button>
        <input id="msg_text" type="text" name="msg_text">
        <button id="msg_button" type="submit" form="msg_form"> Send </button>
        <input id="destr_timer" type="hidden" value="{{ destruct_select.value }}" name="destr_timer">
    </form>
</div>

chat/templates/chat/_new_room_form.html
    <form id="create_room_form" method="post" action="{% url 'chat:create_room' %}">
        {% csrf_token %}
            {{ create_room_form.as_p }}
            <button id="create_room_btn">
                Create!
            </button>

    </form>

chat/templates/chat/_room_list.html
    <div id="rooms_table_div">
        <table id="rooms_table">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Join/quit
                    </th>
                    <th>
                        Status
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for room in rooms %}
                <tr>
                    <td>
                        <a href="/chat/room/{{ room.id }}"> {{ room.room_name }}  </a>
                    </td>
                    <td>
                        <form id="join_room_form_{{ room.id }}" action="/chat/room/{{ room.id }}" method="post">
                            {% csrf_token %}
                            <button name="join_room_btn" type="submit" value="{{ room.id }}">
                                Join
                            </button>
                        </form>
                    </td>
                    <td>
                        {% if room.private %}
                            Private
                        {% else %}
                            Public
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

chat/templates/chat/chat.html
{% extends 'website/base.html' %}

{% block content %}
<div id="chat_div">
    <div id="friends_div">
        {% include 'chat/_friend_list.html' %}
    </div>

    <div id="chat_window">
        {% include 'chat/_chat_top.html' %}
        {% include 'chat/_chat_window.html' %}
        {% include 'chat/_message_form.html' %}
    </div>

    <div id="rooms_div">
        {% include 'chat/_new_room_form.html' %}
        {% include 'chat/_room_list.html' %}
    </div>

</div>
{% endblock %}


{% block js %}

    <script type="text/javascript">

        {% if friend %}
            var friend_id = '{{ friend.id }}';
            console.log(friend_id);
        {% elif room %}
            var room_id = {{ room.id }};
        {% endif %}

    </script>
    <script src="{% static 'js/chat.js' %}"></script>


{% endblock %}